name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        cluster: [v1.11.10, v1.12.10, v1.14.6, v1.16.3, v1.17.0]

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      if: matrix.cluster != 'v1.11.10'
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
